tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8009
    enabled: true
server:
  port: 80
---
spring:
  profiles:
    active: dev
logging:
  level:
    root: info
#---
#spring:
#  profiles:
#    active: prod
#logging:
#  level:
#    root: info